### ISSUE TITLE
Song count

### ISSUE THREAD

**Issue by TheJJ100100** [APIADay/SoundCloud#2]
The number saying which song the user is on currently starts at 0, it would look better if it started at 1 and went up to `allTracks.length` amount.

It currently does: http://www.giphy.com/gifs/l46CyOVXfnUAjvu5q

It should do: http://www.giphy.com/gifs/l41YtsnBJ2hDvid0c

**Comment by TheJJ100100** [comment]
https://github.com/APIADay/SoundCloud/pull/3

**Comment by gmemstr** [comment]
Rule #1, but thanks I'll merge it anyways. https://github.com/APIADay/Rules-About

**Comment by TheJJ100100** [comment]
@gmemstr Oh, didn't see that. Sorry.
